vich_uploader:
    db_driver: orm
    mappings:
        logment_image:
             uri_prefix: /images/logements
             upload_destination: "%kernel.project_dir%/public/images/logements"
             namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
